<?php
/**
 *
 * QuickInstall development fixtures
 *
 * @copyright (c) 2026 phpBB Limited <https://www.phpbb.com>
 * @license       GNU General Public License, version 2 (GPL-2.0)
 *
 */

namespace QuickInstallSeed;

use RuntimeException;

class ContentBuilder extends BaseBuilder
{
	private $users;
	private $forums;
	private $posters;
	private $posterIndex = 0;

	public function seed(array $users, array $forums): array
	{
		$this->users = $users;
		$this->forums = $forums;
		$this->posters = $users['posters'];
		$items = [];
		$iconId = $this->firstIcon();

		$items['announcement'] = $this->createTopic(
			$forums['news'],
			$users['admin'],
			'Announcement topic',
			'This announcement is shown more prominently than a regular topic in this forum.',
			POST_ANNOUNCE
		);
		$items['sticky'] = $this->createTopic(
			$forums['news'],
			$users['admin_2'],
			'Sticky topic',
			'This sticky stays near the top of the topic list so important information is easy to find.',
			POST_STICKY
		);
		$items['normal'] = $this->createTopic(
			$forums['lobby'],
			$users['regular'],
			'Normal topic',
			'This is a regular topic with no special status. Members can read it and add replies normally.'
		);
		$items['locked'] = $this->createTopic(
			$forums['lobby'],
			$users['admin'],
			'Locked topic',
			'This topic has been locked. Members can still read it, but they cannot add new replies.'
		);
		$this->context->db->sql_query('UPDATE ' . TOPICS_TABLE . '
			SET topic_status = ' . ITEM_LOCKED . '
			WHERE topic_id = ' . $items['locked']['topic_id']);
		$this->addModeratorLog(
			$users['admin'],
			$forums['lobby'],
			$items['locked']['topic_id'],
			'LOG_LOCK',
			[$this->context->prefix . 'Locked topic']
		);
		$items['icon'] = $this->createTopic(
			$forums['lobby'],
			$users['regular_2'],
			'Topic with icon',
			'This regular topic has an icon beside its title so you can check how topic icons are displayed.',
			POST_NORMAL,
			['icon_id' => $iconId]
		);
		$items['global'] = $this->createTopic(
			$forums['lobby'],
			$users['moderator'],
			'Global announcement',
			'This global announcement can appear across the board instead of belonging to only one forum.',
			POST_GLOBAL
		);
		$items['moved_target'] = $this->createTopic(
			$forums['lobby'],
			$users['regular_3'],
			'Moved topic destination',
			'This is the destination of a moved topic. The original forum contains a redirect that points here.'
		);
		$items['moved_redirect'] = [
			'topic_id' => $this->createMovedRedirect($forums['read'], $items['moved_target']['topic_id']),
			'post_id' => 0,
		];
		$this->addModeratorLog(
			$users['moderator'],
			$forums['read'],
			$items['moved_target']['topic_id'],
			'LOG_MOVE',
			[$this->forumName($forums['read']), $this->forumName($forums['lobby'])]
		);

		$sectionNames = [
			'news' => 'News forum',
			'lobby' => 'Lobby forum',
			'read' => 'Read forum',
			'unread' => 'Unread forum',
			'parent' => 'Parent forum',
			'locked_forum' => 'Locked forum',
			'password' => 'Password-protected forum',
			'private' => 'Private forum',
			'icon' => 'Forum with icon',
			'child_a' => 'Child subforum A',
			'child_b' => 'Child subforum B',
		];
		foreach ($forums as $key => $forumId)
		{
			if (in_array($key, ['link', 'empty'], true))
			{
				continue;
			}
			for ($number = 1; $number <= 3; $number++)
			{
				$this->createTopic(
					$forumId,
					$this->nextPoster(),
					sprintf('%s topic %d', $sectionNames[$key] ?? ucfirst(str_replace('_', ' ', $key)), $number),
					sprintf(
						'This is topic %d in the %s. It has a short opening message and works like a regular discussion.',
						$number,
						$sectionNames[$key] ?? ucfirst(str_replace('_', ' ', $key))
					)
				);
			}
		}

		$items += $this->seedRichPosts();
		$items += $this->seedPolls();
		$this->context->setMeta('content', $items);
		$this->context->restoreUser();
		return $items;
	}

	public function seedVolume(array $forums, array $users, int $topicCount, int $replyCount): void
	{
		if (!$forums || !$users)
		{
			throw new RuntimeException('Seed preset requires forums and posting users.');
		}

		for ($topic = 1; $topic <= $topicCount; $topic++)
		{
			$forumId = $forums[($topic - 1) % count($forums)];
			$label = sprintf('Topic %03d', $topic);
			$item = $this->createTopic(
				$forumId,
				$users[($topic - 1) % count($users)],
				$label,
				sprintf('This is topic %d generated by the %s preset.', $topic, $this->context->preset)
			);

			for ($reply = 1; $reply <= $replyCount; $reply++)
			{
				$this->createReply(
					$item['topic_id'],
					$forumId,
					$users[($topic + $reply - 1) % count($users)],
					$label,
					sprintf('This is reply %d of %d in topic %d.', $reply, $replyCount, $topic),
					sprintf('page-%02d', $reply)
				);
			}

			if ($topic % 10 === 0)
			{
				$this->context->saveManifest();
				$GLOBALS['cache']->purge();
				gc_collect_cycles();
			}
		}
		$this->context->restoreUser();
	}

	private function seedRichPosts(): array
	{
		$items = [];
		$items['bbcode'] = $this->createTopic(
			$this->forums['lobby'],
			$this->users['regular'],
			'BBCode and smiley showcase',
			'This topic includes common BBCode, lists, a code block, a quote, links, and smileys.'
		);
		$bbcode = 'This reply shows several formatting options in one place.

[b]Bold text[/b], [i]italic text[/i], [u]underlined text[/u], and [s]strikethrough text[/s].
[color=red]Red text[/color], [color=#00AA00]green text[/color], and [color=blue]blue text[/color].
[size=50]Smaller text[/size] and [size=150]larger text[/size].

[quote="Sample user"]This quote also includes [url=https://www.phpbb.com/]a link[/url].[/quote]

[code]function welcome($name) {
	return "Welcome, " . $name;
}[/code]

[list]
[*]First item
[*]Second item
[list=a]
[*]First alphabetical item
[*]Second alphabetical item
[/list]
[/list]

[list=1]
[*]First numbered item
[*]Second numbered item
[/list]

Common smileys: :) :D ;) :( :o :? 8-) :lol: :x :P :oops: :cry: :evil: :twisted: :roll: :!: :idea: :arrow: :geek: :ugeek:';
		$items['bbcode_reply'] = [
			'topic_id' => $items['bbcode']['topic_id'],
			'post_id' => $this->createReply(
				$items['bbcode']['topic_id'],
				$this->forums['lobby'],
				$this->users['moderator'],
				'BBCode and smiley showcase',
				$bbcode,
				'bbcode'
			),
		];

		$items['quotes'] = $this->createTopic(
			$this->forums['lobby'],
			$this->users['regular_2'],
			'Deep quote nesting',
			'This topic contains a reply with three quote levels so deeply nested quotes are easy to find.'
		);
		$this->createReply(
			$items['quotes']['topic_id'],
			$this->forums['lobby'],
			$this->users['admin'],
			'Deep quote nesting',
			'[quote="User one"][quote="User two"][quote="User three"]Innermost quote.[/quote]Second-level reply.[/quote]First-level reply.[/quote]This text appears after all three quote levels.',
			'quotes'
		);

		$items['overflow'] = $this->createTopic(
			$this->forums['lobby'],
			$this->users['regular_3'],
			'Long content and overflow',
			'This topic contains a long link and a wide code block so wrapping and horizontal overflow are easy to find.'
		);
		$this->createReply(
			$items['overflow']['topic_id'],
			$this->forums['lobby'],
			$this->users['moderator_2'],
			'Long content and overflow',
			'This unbroken word checks that long text wraps without stretching the page:
SupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidocious

This long address checks link wrapping:
https://example.test/events/summer-community-picnic/registration/this-is-an-intentionally-long-address-without-any-natural-break-points

[code]------------------------------------------------------------------------------------------------------------------------
This line is intentionally wide and should remain readable without breaking the surrounding page.
------------------------------------------------------------------------------------------------------------------------[/code]',
			'overflow'
		);

		$items['pagination'] = $this->createTopic(
			$this->forums['lobby'],
			$this->users['admin'],
			'Pagination topic',
			'This topic has 40 approved replies plus one reply waiting for approval, creating multiple topic pages.'
		);
		for ($number = 1; $number <= 40; $number++)
		{
			$this->createReply(
				$items['pagination']['topic_id'],
				$this->forums['lobby'],
				$this->nextPoster(),
				'Pagination topic',
				sprintf('This is pagination reply %d of 40.', $number),
				sprintf('page-%02d', $number)
			);
		}
		$unapproved = $this->createReply(
			$items['pagination']['topic_id'],
			$this->forums['lobby'],
			$this->users['regular_3'],
			'Pagination topic',
			'This reply is waiting for moderator approval.',
			'unapproved'
		);
		$this->context->db->sql_query('UPDATE ' . POSTS_TABLE . '
			SET post_visibility = ' . ITEM_UNAPPROVED . '
			WHERE post_id = ' . $unapproved);
		$this->context->db->sql_query('UPDATE ' . TOPICS_TABLE . '
			SET topic_posts_approved = CASE WHEN topic_posts_approved > 0 THEN topic_posts_approved - 1 ELSE 0 END,
				topic_posts_unapproved = topic_posts_unapproved + 1
			WHERE topic_id = ' . $items['pagination']['topic_id']);
		$this->context->addId('unapproved_posts', $unapproved);
		$items['unapproved'] = ['topic_id' => $items['pagination']['topic_id'], 'post_id' => $unapproved];

		return $items;
	}

	private function seedPolls(): array
	{
		$activePoll = [
			'poll_title' => 'Which board area are you reviewing?',
			'poll_options' => ['Extensions', 'Styles', 'Permissions', 'Notifications'],
			'poll_max_options' => 1,
			'poll_length' => 0,
			'poll_vote_change' => 1,
			'poll_start' => time(),
		];
		$votedPoll = [
			'poll_title' => 'How much sample content do you prefer?',
			'poll_options' => ['Focused', 'Balanced', 'Dense', 'Maximum'],
			'poll_max_options' => 1,
			'poll_length' => 0,
			'poll_vote_change' => 0,
			'poll_start' => time(),
		];

		$items = [];
		$items['active_poll'] = $this->createTopic(
			$this->forums['lobby'],
			$this->users['admin'],
			'Active poll',
			'This poll has no votes yet and allows members to change their vote.',
			POST_NORMAL,
			[],
			$activePoll
		);
		$items['voted_poll'] = $this->createTopic(
			$this->forums['lobby'],
			$this->users['admin_2'],
			'Poll with results',
			'This poll already has six votes spread across four choices.',
			POST_NORMAL,
			[],
			$votedPoll
		);
		$this->injectVotes($items['voted_poll']['topic_id']);
		return $items;
	}

	private function injectVotes(int $topicId): void
	{
		$db = $this->context->db;
		$result = $db->sql_query('SELECT poll_option_id FROM ' . POLL_OPTIONS_TABLE . '
			WHERE topic_id = ' . $topicId . '
			ORDER BY poll_option_id ASC');
		$options = [];
		while ($row = $db->sql_fetchrow($result))
		{
			$options[] = (int) $row['poll_option_id'];
		}
		$db->sql_freeresult($result);
		$voters = array_slice($this->posters, 0, 6);
		$distribution = [0, 0, 1, 1, 2, 3];
		$totals = array_fill_keys($options, 0);
		foreach ($voters as $index => $userId)
		{
			$optionId = $options[$distribution[$index]] ?? 0;
			if (!$optionId)
			{
				continue;
			}
			$db->sql_query('INSERT INTO ' . POLL_VOTES_TABLE . ' ' . $db->sql_build_array('INSERT', [
				'topic_id' => $topicId,
				'poll_option_id' => $optionId,
				'vote_user_id' => $userId,
				'vote_user_ip' => '127.0.0.1',
			]));
			$totals[$optionId]++;
		}
		foreach ($totals as $optionId => $total)
		{
			$db->sql_query('UPDATE ' . POLL_OPTIONS_TABLE . '
				SET poll_option_total = ' . $total . '
				WHERE topic_id = ' . $topicId . ' AND poll_option_id = ' . $optionId);
		}
		$db->sql_query('UPDATE ' . TOPICS_TABLE . ' SET poll_last_vote = ' . time() . ' WHERE topic_id = ' . $topicId);
	}

	private function createTopic(
		int $forumId,
		int $userId,
		string $label,
		string $message,
		int $topicType = POST_NORMAL,
		array $additional = [],
		array $poll = []
	): array
	{
		$db = $this->context->db;
		$subject = $this->context->prefix . $label;
		$result = $db->sql_query_limit(
			'SELECT topic_id, topic_first_post_id FROM ' . TOPICS_TABLE . "
				WHERE topic_title = '" . $db->sql_escape($subject) . "'",
			1
		);
		$row = $db->sql_fetchrow($result);
		$db->sql_freeresult($result);
		if ($row)
		{
			$topicId = (int) $row['topic_id'];
			$postId = (int) $row['topic_first_post_id'];
			$this->context->addId('topics', $topicId);
			$this->context->addId('posts', $postId);
			return ['topic_id' => $topicId, 'post_id' => $postId];
		}

		$this->context->switchUser($userId);
		$data = $this->postData($forumId, 0, $subject, $message);
		$data = array_merge($data, $additional);
		submit_post('post', $subject, $this->context->user->data['username'], $topicType, $poll, $data);
		$topicId = (int) ($data['topic_id'] ?? 0);
		$postId = (int) ($data['post_id'] ?? 0);
		if (!$topicId || !$postId)
		{
			throw new RuntimeException("Unable to create seed topic: $subject");
		}
		$this->context->addId('topics', $topicId);
		$this->context->addId('posts', $postId);
		return ['topic_id' => $topicId, 'post_id' => $postId];
	}

	private function createReply(
		int $topicId,
		int $forumId,
		int $userId,
		string $label,
		string $message,
		string $key
	): int
	{
		$db = $this->context->db;
		$suffix = strpos($key, 'page-') === 0 ? ' — reply ' . substr($key, 5) : '';
		$subject = $this->context->prefix . 'Re: ' . $label . $suffix;
		$result = $db->sql_query_limit(
			'SELECT post_id FROM ' . POSTS_TABLE . "
				WHERE topic_id = $topicId
					AND post_subject = '" . $db->sql_escape($subject) . "'",
			1
		);
		$postId = (int) $db->sql_fetchfield('post_id');
		$db->sql_freeresult($result);
		if ($postId)
		{
			$this->context->addId('posts', $postId);
			return $postId;
		}

		$this->context->switchUser($userId);
		$data = $this->postData($forumId, $topicId, $subject, $message);
		$poll = [];
		submit_post('reply', $subject, $this->context->user->data['username'], POST_NORMAL, $poll, $data);
		$postId = (int) ($data['post_id'] ?? 0);
		if (!$postId)
		{
			throw new RuntimeException("Unable to create seed reply: $subject");
		}
		$this->context->addId('posts', $postId);
		return $postId;
	}

	private function postData(int $forumId, int $topicId, string $subject, string $message): array
	{
		$db = $this->context->db;
		$uid = $bitfield = '';
		$options = 7;
		generate_text_for_storage($message, $uid, $bitfield, $options, true, true, true);
		$result = $db->sql_query_limit('SELECT forum_name FROM ' . FORUMS_TABLE . ' WHERE forum_id = ' . $forumId, 1);
		$forumName = (string) $db->sql_fetchfield('forum_name');
		$db->sql_freeresult($result);

		return [
			'forum_id' => $forumId,
			'topic_id' => $topicId,
			'icon_id' => 0,
			'topic_title' => $subject,
			'topic_time_limit' => 0,
			'poster_id' => (int) $this->context->user->data['user_id'],
			'enable_bbcode' => true,
			'enable_smilies' => true,
			'enable_urls' => true,
			'enable_sig' => true,
			'message' => $message,
			'message_md5' => md5($message),
			'bbcode_bitfield' => $bitfield,
			'bbcode_uid' => $uid,
			'post_edit_locked' => 0,
			'notify_set' => false,
			'notify' => false,
			'post_time' => time(),
			'forum_name' => $forumName,
			'enable_indexing' => true,
			'force_approved_state' => true,
		];
	}

	private function createMovedRedirect(int $forumId, int $targetTopicId): int
	{
		$db = $this->context->db;
		$subject = $this->context->prefix . 'Moved topic redirect';
		$result = $db->sql_query_limit(
			'SELECT topic_id FROM ' . TOPICS_TABLE . '
				WHERE forum_id = ' . $forumId . '
					AND topic_status = ' . ITEM_MOVED . '
					AND topic_moved_id = ' . $targetTopicId,
			1
		);
		$id = (int) $db->sql_fetchfield('topic_id');
		$db->sql_freeresult($result);
		if (!$id)
		{
			$db->sql_query('INSERT INTO ' . TOPICS_TABLE . ' ' . $db->sql_build_array('INSERT', [
				'forum_id' => $forumId,
				'icon_id' => 0,
				'topic_title' => $subject,
				'topic_poster' => $this->users['regular_3'],
				'topic_time' => time(),
				'topic_status' => ITEM_MOVED,
				'topic_type' => POST_NORMAL,
				'topic_moved_id' => $targetTopicId,
				'topic_visibility' => ITEM_APPROVED,
			]));
			$id = (int) $db->sql_nextid();
		}
		$this->context->addId('topics', $id);
		return $id;
	}

	private function addModeratorLog(
		int $userId,
		int $forumId,
		int $topicId,
		string $operation,
		array $data
	): void
	{
		$db = $this->context->db;
		$result = $db->sql_query_limit('SELECT log_id FROM ' . LOG_TABLE . "
			WHERE log_type = " . LOG_MOD . '
				AND forum_id = ' . $forumId . '
				AND topic_id = ' . $topicId . "
				AND log_operation = '" . $db->sql_escape($operation) . "'",
			1
		);
		$logId = (int) $db->sql_fetchfield('log_id');
		$db->sql_freeresult($result);
		if (!$logId)
		{
			$logId = (int) $this->context->container->get('log')->add(
				'mod',
				$userId,
				'127.0.0.1',
				$operation,
				false,
				array_merge(['forum_id' => $forumId, 'topic_id' => $topicId], $data)
			);
		}
		if (!$logId)
		{
			throw new RuntimeException("Unable to create development moderator log: $operation");
		}
		$this->context->addId('logs', $logId);
	}

	private function forumName(int $forumId): string
	{
		$result = $this->context->db->sql_query_limit(
			'SELECT forum_name FROM ' . FORUMS_TABLE . ' WHERE forum_id = ' . $forumId,
			1
		);
		$name = (string) $this->context->db->sql_fetchfield('forum_name');
		$this->context->db->sql_freeresult($result);
		return $name;
	}

	private function firstIcon(): int
	{
		$result = $this->context->db->sql_query_limit('SELECT icons_id FROM ' . ICONS_TABLE . ' ORDER BY icons_id ASC', 1);
		$id = (int) $this->context->db->sql_fetchfield('icons_id');
		$this->context->db->sql_freeresult($result);
		return $id;
	}

	private function nextPoster(): int
	{
		$id = $this->posters[$this->posterIndex % count($this->posters)];
		$this->posterIndex++;
		return $id;
	}
}
